# Generated by Django 5.2.4 on 2025-08-04 06:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoringData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('container_code', models.CharField(max_length=50)),
                ('pallet_position', models.CharField(max_length=20)),
                ('product_description', models.TextField()),
            ],
        ),
    ]
